config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update]do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
    get "/search" => "searches#search"

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_tag_relations, dependent: :destroy
  has_many :tags, through: :book_tag_relations

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


def save_tags(savebook_tags)
  current_tags = self.tags.pluck(:name) unless self.tags.nil?
  old_tags = current_tags - savebook_tags
  new_tags = savebook_tags - current_tags

  old_tags.each do |old_name|
    self.tags.delete Tag.find_by(name:old_name)
  end

  new_tags.each do |old_name|
    book_tag = Tag.find_or_create_by(name:new_name)
    self.tags << book_tag
  end
end


  def self.search_for(word,search)
    if search == "perfect"
      Book.where(title: word)
    elsif search == "forward"
      Book.where("title LIKE?","#{word}%")
    elsif search == "backward"
      Book.where("title LIKE?","%#{word}")
    else
      Book.where("title LIKE?","%#{word}%")
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all.order(params[:sort])
    @user = User.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    tag = params[:book][:name].split(',')
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end



  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end

  def is_matching_login_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to (books_path) unless @user == current_user
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
　　　<table>
       <% book.book_comments.each do |book_comment| %>
          <tr>
           <td><%= link_to user_path(book_comment.user), remote: true do %>
             <%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
               <%= book_comment.user.name %>
             <% end %>
           </td>

           <td><%= book_comment.comment %></td>
               <% if book_comment.user == current_user %>
              <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger", remote: true %></td>
            <% end %>


          </tr>
       <% end %>
　　　</table>

　　　<%= form_with(model: [book,book_comment],local: false) do |f| %>
             <%= f.text_area :comment, class: "form-control", id:"text_area" %>
             <%= f.submit "送信" %>
          <% end %>

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    ♥<%= book.favorites.count %>
  <% end %>

  <% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    ♡<%= book.favorites.count %>
  <% end %>

<% end %>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>


  <div class="form-group">
    <%= f.label "Tag" %>
    <%= f.text_field :tag_name, class: 'form-control tag_name' %>
  </div>


  <% if book.id.nil? %>
    <div class= "form-group" id="star">
      <%= f.label :rate %>
      <%= f.hidden_field :rate, id: :review_star, class: 'form-control' %>
      <div id="post_raty"></div>
    </div>

    <script>
      $(document).on('turbolinks:load', function(){
        let elem = document.querySelector('#post_raty');
        if (elem == null) return;

        elem.innerHTML = ""
        let opt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[rate]',
        };
        raty(elem, opt);
      });
    </script>
  <% else %>
    <div class= "form-group">
      <%= render "static_rate", book: book %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>

        <td id= "favorite-<%= book.id %>">
          <%= render 'books/favorite', book: book %>
          </td>

        <td>コメント数: <%= "#{book.book_comments.count}" %></td>

        <td><%= render "books/static_rate", book: book %></td>

        <td><% l book.created_at %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_static_rate.html.erb
<div id="rate_<%= book.id %>"></div>

<script>

  $(document).on('turbolinks:load', function(){
    let elem = document.querySelector('rate_<%= book.id %>');
    if (elem == null) return;

    elem.innerHTML = "";
    let opt = {
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= book.rate %>",
    readOnly: true,
    };
    raty(elem, opt);
  });
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>

  		<%= render 'layouts/errors', obj: @book %>

  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>

  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>

        <%= render 'layouts/errors', obj: @book %>

      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>

        <%= link_to '新しい順',books_path(sort: "created_at desc") %>|
        <%= link_to '評価の高い順', books_path(sort: 'rate desc') %>

      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>

    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>


      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>

    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td>
            <% @book.tags.each do |tag| %>
            <li style= "list-style: none;"><%= link_to tag.name, search_path(content: tag.name, model:"tag", method: "perfect") %></li>
            <% end %>
          </td>
          <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
          <td id= "favorite-<%= @book.id %>">
          <%= render 'favorite', book: @book %>
          </td>
          <td>コメント数: <%= @book.book_comments.count %></td>
        </tr>
      </table>

        <div id= "comment">
         <%= render 'comment', book: @book, book_comment: @book_comment %>
        </div>

    </div>

  </div>
</div>